apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  custom.conf: |
    server {
        listen 8000;
        root /homework/conf;
        index file;
        location /conf {
            try_files $uri $uri/ =404;
        }
    }